### ISSUE TITLE
uvindex error

### ISSUE THREAD

**Issue by ctelroy** [kevinresol/hk-weather#1]
Hi Kelvin, after testing, the data from HKWeather like this  ```uvindex:""``` creates an error.
Maybe can solve it by create```abstract UvindexData(String) from String to String {}``` in line 43 Weather.hx.
But, it still need to handle if the data is ```
         data:Array<{place:String, value:Int, desc:String}>; 
	 recordDesc:String;```

**Comment by kevinresol** [comment]
`"uvindex":{"data":[{"place":"京士柏","value":9,"desc":"甚高"}],"recordDesc":"過去一小時"}`
`"uvindex:""`
